# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquotes', '0003_quote_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brithday',
            field=models.DateField(null=True),
        ),
    ]
