# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myquotes', '0004_user_brithday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='brithday',
            new_name='birthday',
        ),
    ]
